# Generated by Django 5.2.4 on 2025-07-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='followed_actors',
            field=models.ManyToManyField(blank=True, related_name='actor_followers', to='app.actor'),
        ),
    ]
