# Generated by Django 5.2.4 on 2025-08-01 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_followed_actors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollowedartist',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='userfollowedartist',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserFollowedActor',
        ),
        migrations.DeleteModel(
            name='UserFollowedArtist',
        ),
    ]
