# Generated by Django 5.2.4 on 2025-08-01 07:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_userfollowedartist_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='Bu etkinlikle ilişkili oyuncuyu seçin .', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_by_actor', to='app.actor'),
        ),
        migrations.AddField(
            model_name='event',
            name='artist',
            field=models.ForeignKey(blank=True, help_text='Bu etkinlikle ilişkili sanatçıyı seçin.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_by_artist', to='app.artist'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('notification_type', models.CharField(choices=[('new_event', 'Yeni Etkinlik'), ('ticket_deal', 'Avantajlı Bilet'), ('general', 'Genel')], default='general', max_length=20)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
