# Generated by Django 5.2.4 on 2025-08-01 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_event_created_by_event_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
