# Generated by Django 5.2.4 on 2025-08-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_event_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('C', 'Customer'), ('S', 'Seller')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('concert', 'Concert'), ('cinema', 'Cinema'), ('theatre', 'Theatre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_event', 'New Event'), ('ticket_deal', 'Advantageous Ticket'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('A', 'A Type'), ('B', 'B Type'), ('C', 'C Type')], max_length=1),
        ),
    ]
