# Generated by Django 5.2.4 on 2025-08-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_customuser_user_type_alter_event_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('C', 'Customer'), ('S', 'Seller')], default='C', max_length=1),
        ),
    ]
