# Generated by Django 5.2.4 on 2025-08-07 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_ticket_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='Select the actor associated with this event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_by_actor', to='app.actor'),
        ),
        migrations.AlterField(
            model_name='event',
            name='artist',
            field=models.ForeignKey(blank=True, help_text='Select the artist associated with this event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_by_artist', to='app.artist'),
        ),
    ]
