# Generated by Django 5.2.4 on 2025-08-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_event_actor_alter_event_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=8),
        ),
    ]
