# Generated by Django 5.2.4 on 2025-08-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default='21:00'),
            preserve_default=False,
        ),
    ]
