# Generated by Django 5.2.4 on 2025-08-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_on_sale',
            field=models.BooleanField(default=False),
        ),
    ]
