# Generated by Django 5.2.4 on 2025-08-18 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_event_sale_end_time_event_sale_price_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='sale_end_time',
        ),
    ]
