# Generated by Django 5.2.4 on 2025-08-18 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_event_sale_end_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventreview',
            unique_together=set(),
        ),
    ]
