# Generated by Django 5.2.4 on 2025-08-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_eventreview_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default='İstanbul', help_text='City', max_length=100),
            preserve_default=False,
        ),
    ]
