# Generated by Django 5.2.4 on 2025-08-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_event_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='purchase_time',
            field=models.DateTimeField(auto_now_add=True, default='2025-08-26 12:00:00'),
            preserve_default=False,
        ),
    ]
