# Generated by Django 5.2.4 on 2025-09-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_ticket_purchase_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('C', 'Customer'), ('S', 'Seller'), ('A', 'Admin')], default='C', max_length=1),
        ),
    ]
